#!/bin/bash
set -xeuo pipefail
# Verify the bootupd EFI has both grub2 and shim components installed.
# (Note we don't use jq here because that's not available in minimal.)
grep -q 'grub2-.*,shim-' /usr/lib/bootupd/updates/EFI.json
