#!/bin/bash
set -xeuo pipefail
# Verify group members
for grp in kvm tss; do
  # Verify we can find through NSS
  getent group $grp >/dev/null
  # and these need to be directly in /etc
  grep -q $grp /etc/group
done
