apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/fedora/bootc/base-images/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        (event == "push" && target_branch == "main")
      ) && (
        ".tekton/fedora-bootc-42-standard-push.yaml".pathChanged() ||
        "Containerfile".pathChanged() ||
        "bootc-base-imagectl".pathChanged() ||
        "install-manifests".pathChanged() ||
        "fedora-includes/generic.yaml".pathChanged() ||
        "minimal.yaml".pathChanged() ||
        "minimal/***".pathChanged() ||
        "minimal-plus.hidden.yaml".pathChanged() ||
        "minimal-plus/***".pathChanged() ||
        "standard.yaml".pathChanged() ||
        "standard/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-bootc-42
    appstudio.openshift.io/component: fedora-bootc-42-standard
    pipelines.appstudio.openshift.io/type: build
  name: fedora-bootc-42-standard-on-push
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-42-compose:Fedora-42-updates-testing-20250801.0@sha256:906e41132584d4bef60ddd64f006890e80c9e367ceede01dfa4931049191ecb9
    - MANIFEST=fedora-standard
  - name: output-image
    value: quay.io/konflux-fedora/bootc-tenant/fedora-bootc-42-standard:{{revision}}
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:e44129e1977e312ae5d0d080fe88a57ea094c9ebdbdcdb9eeef5dd4378c92c63
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
