apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/fedora/bootc/base-images/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        (event == "push" && target_branch.startsWith("renovate/"))
      ) && (
        ".tekton/fedora-bootc-43-minimal-renovate-push.yaml".pathChanged() ||
        "Containerfile".pathChanged() ||
        "bootc-base-imagectl".pathChanged() ||
        "install-manifests".pathChanged() ||
        "fedora-includes/generic.yaml".pathChanged() ||
        "minimal.yaml".pathChanged() ||
        "minimal/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-bootc-43
    appstudio.openshift.io/component: fedora-bootc-43-minimal
    pipelines.appstudio.openshift.io/type: build
    release.appstudio.openshift.io/auto-release: "false"
  name: fedora-bootc-43-minimal-renovate-on-push
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-43-compose:Fedora-43-updates-20251212.0@sha256:f16c7e8d67220d3b4925d92e9e75857b34ea9f7660329a0bdf8d5b70763a1b6e
    - MANIFEST=fedora-minimal
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/konflux-fedora/bootc-tenant/fedora-bootc-43-minimal:{{revision}}
  - name: labels
    value:
      - org.opencontainers.image.version=43
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:8f5fae793ba663e0654be067bc78055ed146fbcea49cbf85f4b8f8e378684942
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
