apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/fedora/bootc/base-images/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "./fedora-minimal-plus.yaml".pathChanged() || "./fedora-includes/generic.yaml".pathChanged()
      || "./minimal-plus/***".pathChanged() || ".tekton/fedora-bootc-42-minimal-plus-push.yaml".pathChanged()
      || "Containerfile".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-bootc-42
    appstudio.openshift.io/component: fedora-bootc-42-minimal-plus
    pipelines.appstudio.openshift.io/type: build
  name: fedora-bootc-42-minimal-plus-on-push
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-42-compose:Fedora-42-updates-testing-20250610.0@sha256:ad045986a93f76013d9b40c0929d5ffd106d30569890e2c9e115bc44d58f08d7
    - MANIFEST=fedora-minimal-plus
  - name: output-image
    value: quay.io/konflux-fedora/bootc-tenant/fedora-bootc-42-minimal-plus:{{revision}}
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:17ec031131088220ff381c4f74882471ce60905ffe0ee8589481cef475689afb
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
