apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/fedora/bootc/base-images/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        (event == "push" && target_branch == "main")
      ) && (
        ".tekton/fedora-bootc-rawhide-minimal-push.yaml".pathChanged() ||
        "Containerfile".pathChanged() ||
        "bootc-base-imagectl".pathChanged() ||
        "install-manifests".pathChanged() ||
        "fedora-includes/generic.yaml".pathChanged() ||
        "minimal.yaml".pathChanged() ||
        "minimal/***".pathChanged()
      )
    test.appstudio.openshift.io/comment_strategy: "disable_all"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-bootc-rawhide
    appstudio.openshift.io/component: fedora-bootc-rawhide-minimal
    pipelines.appstudio.openshift.io/type: build
  name: fedora-bootc-rawhide-minimal-on-push
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-rawhide-compose:Fedora-Rawhide-20260707.n.0@sha256:f6eda2cf141c9a1362839f654cc80c76a188e38fdd967e0fa87e3f50f663af09
    - MANIFEST=fedora-minimal
  - name: output-image
    value: quay.io/konflux-fedora/bootc-tenant/fedora-bootc-rawhide-minimal:{{revision}}
  - name: labels
    value:
      - org.opencontainers.image.version=45
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:0ad9e06a3c1f64057caaaa1a14f24904036822bb986d43b2d729451c25a399dc
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
  taskRunTemplate:
    serviceAccountName: build-pipeline-fedora-bootc-rawhide-minimal
