apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/fedora/bootc/base-images/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && ( "./standard.yaml".pathChanged() || "./fedora-includes/generic.yaml".pathChanged()
      || "./standard/***".pathChanged() || ".tekton/fedora-bootc-42-standard-pull-request.yaml".pathChanged()
      || "Containerfile".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-bootc-42
    appstudio.openshift.io/component: fedora-bootc-42-standard
    pipelines.appstudio.openshift.io/type: build
  name: fedora-bootc-42-standard-on-pull-request
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-42-compose:Fedora-42-updates-testing-20250619.0@sha256:b215b09f14eb52c6d1f37717eeb6eccb15ca47946735686f3b1e0c8177255e63
    - MANIFEST=fedora-standard
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/konflux-fedora/bootc-tenant/fedora-bootc-42-standard:on-pr-{{revision}}
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:17ec031131088220ff381c4f74882471ce60905ffe0ee8589481cef475689afb
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
